### ISSUE TITLE
Unable to enter realm name when importing character data

### ISSUE THREAD

**Issue by Beeftin** [jwld/completionism-issues#15]
When trying to import new character data, the realm name selection field is not populating or selectable, so the import can't be completed.  Updating information on previously imported characters fails as well which is how I came across this. I tried to re-import my character and found that I could not select my realm.

Edit: Should note that I have the same results when trying in Chrome, Edge, and Firefox.

**Comment by jwld** [comment]
Thanks, I busted it yesterday oops. Fixed now!
