### ISSUE TITLE
Hallow's End Achievements not showing as complete. 

### ISSUE THREAD

**Issue by gizzmo** [jwld/completionism-issues#17]
The achievements [The Horseman's Reins](https://www.wowhead.com/achievement=980/the-horsemans-reins) and [A Frightening Friend
](https://www.wowhead.com/achievement=10365/a-frightening-friend) are not showing as completed.

**Comment by jwld** [comment]
Just pushed an update to how achievs are fetched, are they showing as complete for you now?

**Comment by gizzmo** [comment]
Yes they are. Thanks. Love the awesome site!
