### ISSUE TITLE
Mount missing

### ISSUE THREAD

**Issue by Arcaintink** [jwld/completionism-issues#19]
I currently have Vashj'ir Seahorse but it  is showing as uncollected. My account is synce and I have had it since cata launch. 
![image](https://github.com/jwld/completionism-issues/assets/140156892/5fe53e37-4dd9-4207-90dc-386dd1f72bee)

![image](https://github.com/jwld/completionism-issues/assets/140156892/dab5b894-90be-4501-b758-98f15bc145d9)

**Comment by jwld** [comment]
Hmm that is odd, is it showing as collection on your official armory page?

**Comment by Arcaintink** [comment]
This is my simple armory where it is showing collected also showing collected on my official armory page aswell as data for azeroth

https://simplearmory.com/#/us/thrall/tink/collectable/mounts
https://worldofwarcraft.blizzard.com/en-us/character/us/thrall/tink/collections/mounts
https://www.dataforazeroth.com/characters/US/Thrall/Tink

**Comment by jwld** [comment]
Hm odd, I'll look into it, thanks!

**Comment by jwld** [comment]
@Arcaintink should hopefully be fixed now 🤞 lmk if not
