### ISSUE TITLE
More items not available in-game

### ISSUE THREAD

**Issue by XirevGH** [jwld/completionism-issues#3]
Classic Alchemy:
  Greater Holy Protection Potion

WotLK Alchemy:
  Transmute: Eternal Might

WoD Jewelcrafting: 
  Taladite Amplifier

WoD Inscription:
  Ensorcelled Tarot
  Weapon Crystal
  Mighty Ensorcelled Tarot
  Mighty Weapon Crystal
  Savage Ensorcelled Tarot
  Savage Weapon Crystal

Legion Toys:
  Magi Focusing Crystal

**Comment by jwld** [comment]
Thanks! Should be fixed now, let me know if I missed any ✌️
