### ISSUE TITLE
Wrong Wowhead item links

### ISSUE THREAD

**Issue by XirevGH** [jwld/completionism-issues#4]
All of the Sunwell Plateau Jewelcrafting drops are linking to unavailable non-BoP versions, these are the correct ones:

Design: Amulet of Flowing Life 
https://www.wowhead.com/item=35202/design-amulet-of-flowing-life

Design: Hard Khorium Band 
https://www.wowhead.com/item=35200/design-hard-khorium-band

Design: Hard Khorium Choker
https://www.wowhead.com/item=35203/design-hard-khorium-choker

Design: Loop of Forged Power 
https://www.wowhead.com/item=35198/design-loop-of-forged-power

Design: Pendant of Sunfire 
https://www.wowhead.com/item=35201/design-pendant-of-sunfire

Design: Ring of Flowing Life
https://www.wowhead.com/item=35199/design-ring-of-flowing-life

**Comment by jwld** [comment]
Fixed ta!
