### ISSUE TITLE
Wrong Wowhead links and incorrect tracker

### ISSUE THREAD

**Issue by XirevGH** [jwld/completionism-issues#6]
The Burning Crusade Enchanting recipe "Versatility Prime" is showing "Restore Mana Prime" when mousing over it. 

Seemingly every enchant on the TBC page is linking to the enchant itself and not the recipe, several links are also linking to unavailable versions of the enchants. Too many to list here.

**Comment by jwld** [comment]
Hmm I'll fix that first one. The others I'm aware of - this data is all set automatically using the API and wow.db, so I'll need to investigate why it's being funky with enchanting recipes, would rather avoid having to update them all individually!

**Comment by jwld** [comment]
Fixed now, at last...
